#!/usr/bin/env python3
"""
guest_tracker.py: maintain references/guests.yml of repeat guests.

Two modes:
  --rebuild         scan _corpus_normalized.json, regenerate guests.yml from scratch
  --diff <slug>     emit the file paths + dates for one guest's episodes so the
                    agent can pull excerpts and compare old vs new claims

Repeat-guest matching:
  Normalize guest field by stripping version suffixes (e.g., "Elena Verna 3.0"
  -> "elena verna") and parenthetical companies. Group by normalized name; keep
  groups with >= 2 episodes.

The agent uses --diff <slug> output to extract excerpts for each episode (via
topic_chunks-style filtering on shared seed keywords or just full-file scan)
and detect whether the guest changed stance.
"""
import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")


def normalize_name(s: str) -> str:
    s = re.sub(r"\s+\d+(\.\d+)?$", "", s)
    s = re.sub(r"\s*\(.*?\)\s*", "", s)
    s = s.split(",")[0]
    return s.strip().lower()


def slugify(s: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s


def rebuild(skill_root: Path) -> None:
    norm_path = skill_root / "references" / "_corpus_normalized.json"
    with open(norm_path) as f:
        norm = json.load(f)
    groups: dict[str, list] = defaultdict(list)
    for r in norm["rows"]:
        if r["kind"] != "podcast" or not r.get("guest_or_author"):
            continue
        n = normalize_name(r["guest_or_author"])
        if not n:
            continue
        groups[n].append({
            "date": r.get("date"),
            "id": r["id"],
            "title": r["title"],
            "raw_guest": r["guest_or_author"],
        })

    repeats = {n: sorted(eps, key=lambda x: x.get("date") or "") for n, eps in groups.items() if len(eps) >= 2}

    out = {"guests": {}}
    for name, eps in sorted(repeats.items()):
        slug = slugify(name)
        out["guests"][slug] = {
            "display_name": " ".join(w.capitalize() for w in name.split()),
            "episodes": [{"date": e["date"], "id": e["id"], "title": e["title"]} for e in eps],
            "notes": "",
        }

    out_path = skill_root / "references" / "guests.yml"
    with open(out_path, "w") as f:
        f.write("# Auto-generated by scripts/guest_tracker.py --rebuild. Edit `notes` fields by hand; rerun preserves them only if you merge manually.\n\n")
        yaml.safe_dump(out, f, sort_keys=False, default_flow_style=False)
    print(f"wrote {out_path}: {len(out['guests'])} repeat guests")


def diff(skill_root: Path, slug: str) -> None:
    guests_yml = skill_root / "references" / "guests.yml"
    norm_path = skill_root / "references" / "_corpus_normalized.json"
    with open(guests_yml) as f:
        gdata = yaml.safe_load(f) or {}
    if slug not in (gdata.get("guests") or {}):
        sys.exit(f"guest '{slug}' not in {guests_yml}")
    guest = gdata["guests"][slug]
    with open(norm_path) as f:
        norm = json.load(f)
    by_id = {r["id"]: r for r in norm["rows"]}
    out = {"guest": slug, "display_name": guest.get("display_name"), "episodes": []}
    for ep in guest["episodes"]:
        row = by_id.get(ep["id"])
        if not row:
            continue
        out["episodes"].append({
            "date": ep["date"],
            "id": ep["id"],
            "title": ep["title"],
            "abs_path": row["abs_path"],
            "tags": row.get("tags") or [],
            "word_count": row.get("word_count"),
        })
    print(json.dumps(out, indent=2, ensure_ascii=False))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rebuild", action="store_true")
    ap.add_argument("--diff", default=None, help="guest slug to emit episode pointers for")
    args = ap.parse_args()

    skill_root = Path(__file__).resolve().parent.parent
    if args.rebuild:
        rebuild(skill_root)
    elif args.diff:
        diff(skill_root, args.diff)
    else:
        ap.print_help()


if __name__ == "__main__":
    main()
